<?php
/*
*
* Chill Mode - Admin Interface
* Description: The admin markup, syling and server side scripting
*
*/

if(isset($_POST['chill_hidden']) && $_POST['chill_hidden'] == 'chill_mode') {
  if(1 === check_admin_referer('chill-mode')) {

    $chillModeTitle = $_POST['chillModeTitle'];
    update_option('chillModeTitle', $chillModeTitle);

    $chillModeHeading = $_POST['chillModeHeading'];
    update_option('chillModeHeading', $chillModeHeading);

    $chillModeMessage = $_POST['chillModeMessage'];
    update_option('chillModeMessage', $chillModeMessage);

    $chillModeStyling = stripslashes($_POST['chillModeStyling']);
    update_option('chillModeStyling', $chillModeStyling);

    $chillModeScripts = stripslashes($_POST['chillModeScripts']);
    update_option('chillModeScripts', $chillModeScripts);

    if ( ! function_exists( 'wp_handle_upload' ) ) {
      require_once( ABSPATH . 'wp-admin/includes/file.php' );
    }

    $uploadedfile = $_FILES['chillModeImage'];
    $upload_overrides = array( 'test_form' => false );
    $movefile = wp_handle_upload( $uploadedfile, $upload_overrides );

    if ( $movefile && !isset( $movefile['error'] ) ) {
      update_option('chillModeImage', $movefile);
    } else {
      /**
       * Error generated by _wp_handle_upload()
       * @see _wp_handle_upload() in wp-admin/includes/file.php
       */
      echo '<div class="error fade"><p><div'.$movefile['error'].'</p></div>';
    } ?>

    <div class="updated"><p><strong>Options saved.</strong></p></div><?php
  } else {
    die('Permission denied.');
  }
} else {
  $chillModeTitle = get_option('chillModeTitle');
  $chillModeHeading = get_option('chillModeHeading');
  $chillModeMessage = get_option('chillModeMessage');
  $chillModeStyling = get_option('chillModeStyling');
  $chillModeScripts = get_option('chillModeScripts');
  $chillModeImage = get_option('chillModeImage');
} ?>

<style>

  input {
    width: 100%;
  }
  textarea {
    width: 100%;
    min-height: 100px;
  }
  textarea.customCode {
    font-family: monospace, sans-serif;
    min-height: 200px;
  }
  input.btn {
    width: auto;
    margin-top: 15px;
  }

  /* Maintenance Mode Message */
  #message {
    margin: 20px 15px 0 0;
    padding: 10px 12px;
    border-left: none;
    border-top: 4px solid #dd3d36;
  }
  #message p {
    color: #dd3d36;
    font-size: 30px;
    text-align: center;
  }
  #message p a {
    display: block;
    font-size: 14px;
  }

</style>

<h2>Chill Mode</h2>
<hr>
<p>Edit the page settings for when chill mode is activated.</p>
<hr>
<form name="chill_form_update_options" method="post" action="<?php echo str_replace( '%7E', '~', $_SERVER['REQUEST_URI']); ?>" enctype="multipart/form-data">
  <input type="hidden" name="chill_hidden" value="chill_mode">
  <?php wp_nonce_field('chill-mode'); ?>
  <table class="form-table">
    <tr>
      <th><label for="chillModeTitle">Page Title</label></th>
      <td><input id="chillModeTitle" type="text" name="chillModeTitle" placeholder="We'll be right back." value="<?php echo $chillModeTitle ? $chillModeTitle : ''; ?>"></td>
    </tr>
    <tr>
      <th><label for="chillModeHeading">Heading</label></th>
      <td><input id="chillModeHeading" type="text" name="chillModeHeading" placeholder="Undergoing Maintenance" value="<?php echo $chillModeHeading ? $chillModeHeading : ''; ?>"></td>
    </tr>
    <tr>
      <th><label for="chillModeMessage">Message</label></th>
      <td><textarea id="chillModeMessage" type="text" name="chillModeMessage" placeholder="Hang tight. We'll be right back."><?php echo $chillModeMessage ? $chillModeMessage : ''; ?></textarea></td>
    </tr>
    <tr>
      <th><label for="chillModeImage">Upload Image</label></th>
      <td><input id="chillModeImage" type="file" name="chillModeImage"><?php echo $chillModeImage ? '<img src="'. $chillModeImage['url'] .'">' : ''; ?></td>
    </tr>
  </table>
  <hr>
  <p>Add any custom styling or scripts below. No need to include the HTML tags. Just copy and paste.</p>
  <hr>
  <table class="form-table">
    <tr>
      <th><label for="chillModeStyling">Custom Styles</label></th>
      <td><textarea id="chillModeStyling" type="text" name="chillModeStyling" class="customCode"><?php echo $chillModeStyling ? $chillModeStyling : ''; ?></textarea></td>
    </tr>
    <tr>
      <th><label for="chillModeScripts">Custom Scripts</label></th>
      <td><textarea id="chillModeScripts" type="text" name="chillModeScripts" class="customCode"><?php echo $chillModeScripts ? $chillModeScripts : ''; ?></textarea></td>
    </tr>
  </table>
  <input class="btn button" type="submit" name="Submit" value="Update Settings" />
</form>
